// <auto-generated />
using System;
using GestorPrestaciones;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorPrestaciones.Migrations
{
    [DbContext(typeof(GestorContext))]
    [Migration("20260610065627_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GestorPrestaciones.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseReguladora")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("GradoDiscapacidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Pérez",
                            BaseReguladora = 0,
                            DNI = "12345678A",
                            FechaNacimiento = new DateOnly(1980, 5, 15),
                            GradoDiscapacidad = 0,
                            Nombre = "Juan",
                            Sexo = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "García",
                            BaseReguladora = 0,
                            DNI = "87654321B",
                            FechaNacimiento = new DateOnly(1990, 8, 20),
                            GradoDiscapacidad = 0,
                            Nombre = "María",
                            Sexo = "Femenino"
                        });
                });

            modelBuilder.Entity("GestorPrestaciones.IntervaloBaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("IntervalosBaja");
                });

            modelBuilder.Entity("GestorPrestaciones.IntervaloTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Fin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TrabajoId");

                    b.ToTable("IntervalosTrabajo");
                });

            modelBuilder.Entity("GestorPrestaciones.Prestacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalPerestacion")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Prestaciones");
                });

            modelBuilder.Entity("GestorPrestaciones.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsDeRiesgo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trabajos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Trabajo en minas subterráneas",
                            EsDeRiesgo = true,
                            Nombre = "Minero"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Trabajo en caja de supermercado",
                            EsDeRiesgo = false,
                            Nombre = "Cajero"
                        });
                });

            modelBuilder.Entity("GestorPrestaciones.IntervaloBaja", b =>
                {
                    b.HasOne("GestorPrestaciones.Cliente", "Cliente")
                        .WithMany("BajasLaborales")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestorPrestaciones.IntervaloTrabajo", b =>
                {
                    b.HasOne("GestorPrestaciones.Cliente", "Cliente")
                        .WithMany("Trabajos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorPrestaciones.Trabajo", "Trabajo")
                        .WithMany("IntervalosTrabajo")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("GestorPrestaciones.Prestacion", b =>
                {
                    b.HasOne("GestorPrestaciones.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestorPrestaciones.Cliente", b =>
                {
                    b.Navigation("BajasLaborales");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("GestorPrestaciones.Trabajo", b =>
                {
                    b.Navigation("IntervalosTrabajo");
                });
#pragma warning restore 612, 618
        }
    }
}
